mecanumRobotV2.state()
led.enable(false)
mecanumRobotV2.setLed(LedCount.Left, LedState.OFF)
mecanumRobotV2.setLed(LedCount.Right, LedState.OFF)
let strip = neopixel.create(DigitalPin.P7, 4, NeoPixelMode.RGB)
strip.clear()
mecanumRobotV2.Motor(LR.Upper_left, MD.Forward, 15)
mecanumRobotV2.Motor(LR.Lower_left, MD.Back, 15)
mecanumRobotV2.Motor(LR.Upper_right, MD.Back, 15)
mecanumRobotV2.Motor(LR.Lower_right, MD.Forward, 15)
basic.pause(2000)
mecanumRobotV2.Motor(LR.Upper_left, MD.Forward, 15)
mecanumRobotV2.Motor(LR.Lower_left, MD.Forward, 15)
mecanumRobotV2.Motor(LR.Upper_right, MD.Forward, 15)
mecanumRobotV2.Motor(LR.Lower_right, MD.Forward, 15)
basic.pause(2000)
mecanumRobotV2.Motor(LR.Upper_left, MD.Back, 15)
mecanumRobotV2.Motor(LR.Lower_left, MD.Back, 15)
mecanumRobotV2.Motor(LR.Upper_right, MD.Forward, 15)
mecanumRobotV2.Motor(LR.Lower_right, MD.Forward, 15)
basic.pause(2000)
mecanumRobotV2.state()
basic.forever(function () {
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
})
